-- إضافة البيانات المفقودة في جدول location_translations
INSERT INTO location_translations (location_id, language_id, name, description, meta_title, meta_description, local_keywords, created_at, updated_at) VALUES
(2, 1, 'October Industrial City', 'Fire protection services for October Industrial City', 'Fire Protection October City - Sphinx Fire', 'Professional fire safety services in October Industrial City, Egypt', 'fire protection October City, firefighting systems October industrial zone', NOW(), NOW()),
(2, 2, 'مدينة أكتوبر الصناعية', 'خدمات الحماية من الحريق لمدينة أكتوبر الصناعية', 'الحماية من الحريق مدينة أكتوبر - سفينكس فاير', 'خدمات السلامة من الحريق المهنية في مدينة أكتوبر الصناعية، مصر', 'الحماية من الحريق مدينة أكتوبر، أنظمة مكافحة الحريق المنطقة الصناعية أكتوبر', NOW(), NOW()),
(3, 1, 'Quesna Industrial Zone', 'Fire protection services for Quesna Industrial Zone', 'Fire Protection Quesna - Sphinx Fire', 'Professional fire safety services in Quesna Industrial Zone, Egypt', 'fire protection Quesna, firefighting systems Quesna industrial zone', NOW(), NOW()),
(3, 2, 'المنطقة الصناعية قويسنا', 'خدمات الحماية من الحريق للمنطقة الصناعية قويسنا', 'الحماية من الحريق قويسنا - سفينكس فاير', 'خدمات السلامة من الحريق المهنية في المنطقة الصناعية قويسنا، مصر', 'الحماية من الحريق قويسنا، أنظمة مكافحة الحريق المنطقة الصناعية قويسنا', NOW(), NOW()),
(4, 1, 'Badr Industrial City', 'Fire protection services for Badr Industrial City', 'Fire Protection Badr City - Sphinx Fire', 'Professional fire safety services in Badr Industrial City, Egypt', 'fire protection Badr City, firefighting systems Badr industrial zone', NOW(), NOW()),
(4, 2, 'مدينة بدر الصناعية', 'خدمات الحماية من الحريق لمدينة بدر الصناعية', 'الحماية من الحريق مدينة بدر - سفينكس فاير', 'خدمات السلامة من الحريق المهنية في مدينة بدر الصناعية، مصر', 'الحماية من الحريق مدينة بدر، أنظمة مكافحة الحريق المنطقة الصناعية بدر', NOW(), NOW()),
(5, 1, '10th of Ramadan Industrial City', 'Fire protection services for 10th of Ramadan Industrial City', 'Fire Protection 10th Ramadan - Sphinx Fire', 'Professional fire safety services in 10th of Ramadan Industrial City, Egypt', 'fire protection 10th Ramadan, firefighting systems 10th Ramadan industrial zone', NOW(), NOW()),
(5, 2, 'مدينة العاشر من رمضان الصناعية', 'خدمات الحماية من الحريق لمدينة العاشر من رمضان الصناعية', 'الحماية من الحريق العاشر من رمضان - سفينكس فاير', 'خدمات السلامة من الحريق المهنية في مدينة العاشر من رمضان الصناعية، مصر', 'الحماية من الحريق العاشر من رمضان، أنظمة مكافحة الحريق المنطقة الصناعية العاشر من رمضان', NOW(), NOW()); 